project_id = "agmsvskzasrqnlijtwbg"

[functions.send-auth-email]
verify_jwt = false

[functions.verify-questionnaire]
verify_jwt = false

[functions.confirm-questionnaire-user]
verify_jwt = false

[functions.send-registration-verification]
verify_jwt = false

[functions.verify-registration]
verify_jwt = false

[functions.check-questionnaire-verified]
verify_jwt = false
